### ISSUE TITLE
/r/OpenDirectories search pages

### ISSUE THREAD

**Issue by MineRobber9000** [MineRobber9000/flashgames#1]
I searched [/r/OpenDirectories](https://www.reddit.com/r/opendirectories/search?q=flash+games&restrict_sr=on) for "flash games". Here are some of the results.
## bigdino.com ##
Here is a [dump of games](https://web.archive.org/web/20171109133222/http://bigdino.com:80/games/) from bigdino.com.

Some games it has (that have been archived):
 - Awesome Tanks:
    - Original
    - 2017 verion
    - Sequel
    - Sequel, 2017 version
 - Basket and Ball
 - Clicker Heroes
 - Others

## Foundation for Research and Technology - Hellas (Greece) ##

A member of FORTH had a [large amount of flash games](http://web.archive.org/web/20170824061204/https://elegans.imbb.forth.gr/games/).

Not sure how useful this one will be, but it's there.

## onplayers.com ##

onplayers.com has [lots of games](http://web.archive.org/web/20160424200926/http://onplayers.com:80/games).

TODO: what games are here?

## kuukunen.net ##

Lots of games [here](http://kuukunen.net/flash/games/) (archive [here](https://web.archive.org/web/*/http://kuukunen.net/flash/games/))

## TODO ##

 - [ ] Do a full inventory of what the Wayback Machine has wrt the games
 - [ ] Decide which games are notable enough to be included
 - [ ] Grab the games and put them in `games/`
    - [ ] Fix names

**Comment by MineRobber9000** [comment]
Some notable series that can be found here include the Awesome Tanks series, including (supposedly) some 2017 updates.
