### ISSUE TITLE
Searching through Google

### ISSUE THREAD

**Issue by MineRobber9000** [MineRobber9000/flashgames#2]
This one is just putting variations of `"index of /" flash games` into Google

## KB7TBT ##

KB7TBT's Ham Radio site [has some Flash games](https://www.qsl.net/k/kb7tbt//games/Flash%20Games/).

## Gratis Jogos ##

Gratis Jogos (Brazilian) [has a lot of Flash games](https://www.gratisjogos.com.br/arquivos/games/).

(This one also fits under #1 since it's also in OpenDirectories)

## TODO ##

 - [ ] Do a full inventory of what the site has wrt the games
 - [ ] Decide which games are notable enough to be included
 - [ ] Grab the games and put them in `games/`
    - [ ] Fix names
