### ISSUE TITLE
Open Source Flash petition list

### ISSUE THREAD

**Issue by MineRobber9000** [MineRobber9000/flashgames#3]
The Open Source Flash petition [has some Flash games](https://github.com/open-source-flash/open-source-flash#flash-and-shockwave-as-an-art-medium).

## TODO ##

 - [ ] Do a full inventory of what the petition has wrt the games
 - [ ] Decide which games are notable enough to be included
 - [ ] Grab the games and put them in `games/`
    - [ ] Fix names
