### ISSUE TITLE
Garfield: The Movie special edition 2nd disc games

### ISSUE THREAD

**Issue by MineRobber9000** [MineRobber9000/flashgames#5]
The second disc of Garfield: The Movie's Special Edition release contains Flash games.

## TODO

 - [ ] Determine which games are there
 - [ ] Determine if they will work in the projector
 - [ ] Add to archive
